# Generated by Django 5.2.14 on 2026-05-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('rows_count', models.IntegerField()),
                ('columns_count', models.IntegerField()),
                ('processed_rows', models.IntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Lỗi')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=255)),
                ('sleep_hours', models.FloatField()),
                ('deep_sleep_minutes', models.IntegerField()),
                ('rem_sleep_minutes', models.IntegerField()),
                ('awakenings', models.IntegerField()),
                ('spo2_drop_events', models.IntegerField()),
                ('hrv', models.IntegerField()),
                ('rhr', models.IntegerField()),
                ('consecutive_days', models.IntegerField(default=1)),
                ('target_sleep_hours', models.FloatField(default=8.0)),
                ('wake_time', models.TimeField(default='06:30')),
                ('quality_label', models.CharField(blank=True, max_length=50)),
                ('quality_tone', models.CharField(blank=True, max_length=50)),
                ('recovery_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm_used', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sleep Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
